version: '3.4'

services:
  diplomskipokusaj1:
    image: ${DOCKER_REGISTRY-}diplomskipokusaj1
    build:
      context: .
      dockerfile: DiplomskiPokusaj1/Dockerfile
    ports:
        - "5000:443" 
 
  librarydatabase:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'diplomski'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: